// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccountPreview: typeof import('./components/Settings/left_part/MyAccount/AccountPreview.vue')['default']
    AccountRemoval: typeof import('./components/Settings/left_part/MyAccount/AccountRemoval.vue')['default']
    APIToken: typeof import('./components/Settings/left_part/ApiToken/APIToken.vue')['default']
    Avatar: typeof import('./components/Settings/left_part/MyAccount/Avatar.vue')['default']
    ButtonsBack: typeof import('./components/UserProfile/ButtonsBack.vue')['default']
    ChangeColor: typeof import('./components/Settings/left_part/UserProfile/ChangeColor.vue')['default']
    ChangeLanguage: typeof import('./components/Settings/left_part/UserProfile/ChangeLanguage.vue')['default']
    ChangeUsername: typeof import('./components/Settings/left_part/UserProfile/ChangeUsername.vue')['default']
    ContentBlock: typeof import('./components/ContentIndexPage/ContentBlock.vue')['default']
    DeleteAccountPopup: typeof import('./components/Settings/left_part/MyAccount/DeleteAccountPopup.vue')['default']
    DeleteWarning: typeof import('./components/Note/DeleteWarning.vue')['default']
    EditAvatarPopup: typeof import('./components/Settings/left_part/UserProfile/EditAvatarPopup.vue')['default']
    EditInformation: typeof import('./components/Settings/left_part/MyAccount/EditInformation.vue')['default']
    EditNote: typeof import('./components/Note/EditNote.vue')['default']
    ErrorIndicator: typeof import('./components/ErrorIndicator.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header/Header.vue')['default']
    HeaderButton: typeof import('./components/Header/HeaderButton.vue')['default']
    HomePage: typeof import('./components/Home/HomePage.vue')['default']
    LandingPage: typeof import('./components/Home/LandingPage.vue')['default']
    LoginSignupForm: typeof import('./components/LoginSignup/LoginSignupForm.vue')['default']
    LoginSignupFormInput: typeof import('./components/LoginSignup/LoginSignupFormInput.vue')['default']
    LoginSignupText: typeof import('./components/LoginSignup/LoginSignupText.vue')['default']
    MyAccount: typeof import('./components/Settings/left_part/MyAccount/MyAccount.vue')['default']
    NavButtons: typeof import('./components/Home/NavButtons.vue')['default']
    Notes: typeof import('./components/UserProfile/Notes.vue')['default']
    NoteView: typeof import('./components/Note/NoteView.vue')['default']
    OneButtonBack: typeof import('./components/SocialMedia/OneButtonBack.vue')['default']
    PopupCheck: typeof import('./components/Note/PopupCheck.vue')['default']
    PopupCheckDel: typeof import('./components/Note/PopupCheckDel.vue')['default']
    ProfileBlock: typeof import('./components/UserProfile/ProfileBlock.vue')['default']
    ResetTokenPopup: typeof import('./components/Settings/left_part/ApiToken/ResetTokenPopup.vue')['default']
    Right_part: typeof import('./components/Settings/Right_part.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideButton: typeof import('./components/Settings/right_part/SideButton.vue')['default']
    UserProfile: typeof import('./components/Settings/left_part/UserProfile/UserProfile.vue')['default']
    UserProfilePicture: typeof import('./components/User/UserProfilePicture.vue')['default']
    UserSettings: typeof import('./components/Settings/left_part/UserProfile/UserSettings.vue')['default']
  }
}

export {}
