// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ErrorIndicator: typeof import('./components/ErrorIndicator.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header/Header.vue')['default']
    HeaderButton: typeof import('./components/Header/HeaderButton.vue')['default']
    LoginSignupForm: typeof import('./components/LoginSignup/LoginSignupForm.vue')['default']
    LoginSignupFormInput: typeof import('./components/LoginSignup/LoginSignupFormInput.vue')['default']
    LoginSignupText: typeof import('./components/LoginSignup/LoginSignupText.vue')['default']
    NavButtons: typeof import('./components/Home/NavButtons.vue')['default']
    PopupCheck: typeof import('./components/Note/PopupCheck.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
