stages:
  - lint
  - test
  - deploy
  
lint-job:
  before_script:
    - ./ci/before_script.sh
  stage: lint
  script:
    - ./ci/lint-job.sh
  tags: 
    - main
  variables:
    GIT_CLEAN_FLAGS: none
  # rules:
  #   - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  #     when: always
  #   - if: $CI_COMMIT_BRANCH == "dev"
  #     when: always
  #   - when: never
test-job:
  stage: test
  script:
    - ./ci/test_job.sh
  artifacts:
    when: always
    reports:
      junit: report.xml

  tags: 
    - main
  variables:
    GIT_CLEAN_FLAGS: none
  # rules:
  #   - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  #     when: always
  #   - if: $CI_COMMIT_BRANCH == "dev"
  #     when: always
  #   - when: never
deploy-job:
  stage: deploy
  script:
    - export DASHCODE_API_HOST=${DASHCODE_API_HOST}
    - docker-compose build --parallel
    - docker-compose stop
    - docker-compose rm -f
    - docker-compose up -d
  tags:
    - main
  variables:
    GIT_CLEAN_FLAGS: none
  # rules:
  #   - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  #     when: always
  #   - if: $CI_COMMIT_BRANCH == "dev"
  #     when: always
  #   - when: never
