"""Change user.profile_picture_filename to nullable and default=None

Revision ID: 6423f75e3a96
Revises: 9a58c45aa873
Create Date: 2022-05-10 10:45:40.310104

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '6423f75e3a96'
down_revision = '9a58c45aa873'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_picture_filename',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_picture_filename',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    # ### end Alembic commands ###
