"""Add jwt_proof to user

Revision ID: 8fa304747497
Revises: f3bc4af198b5
Create Date: 2022-05-26 20:39:53.661350

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '8fa304747497'
down_revision = 'f3bc4af198b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('jwt_proof', sa.String(length=12), nullable=False, server_default='0123456789ab'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'jwt_proof')
    # ### end Alembic commands ###
