"""Add 'tags' table

Revision ID: 9a58c45aa873
Revises: 42a15f79d8b2
Create Date: 2022-04-26 18:00:37.997377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a58c45aa873'
down_revision = '42a15f79d8b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note_tag_association',
    sa.Column('note_id', sa.String(length=12), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('note_id', 'tag_id')
    )
    op.add_column('notes', sa.Column('content', sa.Text(), nullable=False))
    op.drop_column('notes', 'context')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('context', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('notes', 'content')
    op.drop_table('note_tag_association')
    op.drop_table('tags')
    # ### end Alembic commands ###
