"""Added reference to notes in User object

Revision ID: a09b45570e26
Revises: 333ef80ff817
Create Date: 2022-04-25 20:54:59.374758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a09b45570e26'
down_revision = '333ef80ff817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
