"""Add row_id to notes

Revision ID: f3bc4af198b5
Revises: 6423f75e3a96
Create Date: 2022-05-22 18:49:31.829730

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'f3bc4af198b5'
down_revision = '6423f75e3a96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('row_id', sa.Integer(), sa.Identity(always=False, start=0, increment=1, minvalue=0), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'row_id')
    # ### end Alembic commands ###
