"""empty message

Revision ID: 3006404767fe
Revises: f97eed4ca63d
Create Date: 2022-03-21 15:24:42.820583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3006404767fe'
down_revision = 'f97eed4ca63d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_color', sa.String(length=6), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_color')
    # ### end Alembic commands ###
