"""empty message

Revision ID: 4559d6e657fc
Revises: 3006404767fe
Create Date: 2022-03-21 19:25:06.253283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4559d6e657fc'
down_revision = '3006404767fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture_filename', sa.String(length=40), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_picture_filename')
    # ### end Alembic commands ###
