"""empty message

Revision ID: 883132297a62
Revises: 42bb572d67f8
Create Date: 2022-04-01 20:02:13.557479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '883132297a62'
down_revision = '42bb572d67f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'link',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'link',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
