"""empty message

Revision ID: b00e7914948b
Revises: c2e68c7e14f8
Create Date: 2022-03-15 18:25:06.013427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b00e7914948b'
down_revision = 'c2e68c7e14f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_api_key_expiration_date', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', '_api_key_expiration_date')
    # ### end Alembic commands ###
