version: "3.7"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./.redis-data:/data
    command: --save 60 100
    restart: unless-stopped

  postgres:
    image: postgres
    environment:
      - "POSTGRES_USER=user"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=backend"
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
