[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra"
asyncio_mode = "auto"
testpaths = [
    "tests",
]
filterwarnings = [
    "ignore::DeprecationWarning",
]

[tool.mypy]
python_version = "3.10"
files = [
    "src",
    "tests",
    "run.py",
]
plugins = [
    "sqlalchemy.ext.mypy.plugin",
    "strawberry.ext.mypy_plugin",
]

[[tool.mypy.overrides]]
module = [
    "authlib.jose.*",
    "dynaconf",
    "i18n",
    "testcontainers.*",
    "uvicorn",
]
ignore_missing_imports = true

[tool.black]
line-length = 88
target-version = ['py310']
skip-string-normalization = true
include = "run\\.py|src|tests"
preview = true
