[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra"
asyncio_mode = "auto"
testpaths = [
    "tests",
]
filterwarnings = [
    "ignore::DeprecationWarning",
]

[tool.mypy]
files = [
    "src",
    "tests",
]
plugins = [
    "sqlalchemy.ext.mypy.plugin",
    "strawberry.ext.mypy_plugin",
]

[[tool.mypy.overrides]]
module = [
    "dynaconf",
    "authlib.jose.*",
    "testcontainers.*",
]
ignore_missing_imports = true
